name: MATLAB Build

on:
  pull_request:
    paths:
    - "**.m"
    - ".github/workflows/build-test-matlab.yaml"
  schedule:
      - cron: "30  1  *  *  1"

jobs:
  test-on-matlab:
    name: MATLAB build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: run_all_tests
