on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      # The exit status for grep -q is 0 if a match is found, 1 if not fund
      - name: confirm that Version.is_development is 0
        run: grep -q "Version.is_development = 0;" vbr/support/vbr_version.m
      - name: confirm that the release tag matches release_notes.md
        run: grep -q ${{ github.ref }} release_notes.md
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "release_notes.md"
          draft: true
          tag: ${{ github.ref }}
          prerelease: false
          name: Release ${{ github.ref }}
